on: [push]
jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run JMeter Tests
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: jmeter-files/test-plan.jmx
          args: ""
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl
      - name: Install Latency Lingo
        run: curl -L https://github.com/AnthonyBobsin/latency-lingo-cli/releases/download/v1.3.1/latency-lingo-cli_1.3.1_Linux_x86_64.tar.gz | tar -xz
      - name: Publish to Latency Lingo
        run: ./latency-lingo-cli publish --file result.jtl --api-key $LATENCY_LINGO_API_KEY --label 'Checkout Flow Automated Test Plan'
        env:
          LATENCY_LINGO_API_KEY: ${{ secrets.LATENCY_LINGO_API_KEY }}
